# template

credentialsSecret: anchore-credentials
anchoreEndpoint: "<your-anchore-endpoint>" # modify this
policySelectors:
  - Selector:
      ResourceType: "image"
      SelectorKeyRegex: ".*"
      SelectorValueRegex: ".*"
    PolicyReference:
      Username: "<your-anchore-username>" # modify this
      # This is the default bundle id in anchore engine
      PolicyBundleId: "2c53a13c-1765-11e8-82ef-23527761d060"
    # Mode is one of: "policy", "analysis", or "breakglass". policy=>require policy pass, analysis=>require image analyzed, breakglass=>do nothing
    Mode: policy
# Request analysis of images if not already analyzed. This is the default if the above two are false, but is ignored if strict gating or analysis gating are true
requestAnalysis: true