# template

credentialsSecret: anchore-credentials
anchoreEndpoint: "<your-anchore-endpoint>" # modify this
policySelectors: # add more Selectors to your preference
  - Selector:
      ResourceType: "image"
      SelectorKeyRegex: ".*"
      SelectorValueRegex: ".*"
    PolicyReference:
      Username: "<your-anchore-username>" # modify this
      # This is the default bundle id in anchore engine
      PolicyBundleId: "2c53a13c-1765-11e8-82ef-23527761d060" # add your PolicyBundleId
    # Mode is one of: "policy", "analysis", or "breakglass". policy=>require policy pass, analysis=>require image analyzed, breakglass=>do nothing
    Mode: policy # modify this to your preference
requestAnalysis: true # modify this to your preference